# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityfinderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='institution_id',
            field=models.IntegerField(default=None),
        ),
    ]
