# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityfinderapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='col',
            name='id',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='walk',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='id',
        ),
        migrations.AlterField(
            model_name='academic',
            name='campus_zip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='institution_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='academic',
            name='institution_state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='col',
            name='city',
            field=models.CharField(default='City', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='col',
            name='grocery',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='col',
            name='health',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='col',
            name='housing',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='col',
            name='misc',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='col',
            name='total_index',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='col',
            name='transport',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='col',
            name='utilities',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='aggrev_assault',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='arson',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='bulglary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='car_theft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='city',
            field=models.CharField(default='City', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crime',
            name='larceny_theft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='murder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='property_crime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='rape',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='robbery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='violent_crime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='bed_1_med_price',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='bed_2_med_price',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='city',
            field=models.CharField(default='City', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='walk',
            name='bike_score',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='walk',
            name='city',
            field=models.CharField(default='City', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='walk',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='avg_annual_precip_in',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='avg_annual_precip_in_days',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='avg_annual_precip_snowfall',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='avg_temp_july',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='avg_temp_oct',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.CharField(default='City', max_length=20, primary_key=True, serialize=False),
        ),
    ]
