# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityfinderapp', '0002_auto_20160211_0401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic',
            old_name='campus_add',
            new_name='add',
        ),
        migrations.RenameField(
            model_name='academic',
            old_name='campus_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='academic',
            old_name='campus_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='accreditation',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='accreditation_date_type',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='accreditation_status',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='campus_state',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='campus_zip',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='institution_add',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='institution_city',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='institution_state',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='institution_zip',
        ),
        migrations.AddField(
            model_name='academic',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academic',
            name='zip_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
