# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityfinderapp', '0002_auto_20160210_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col',
            name='city',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crime',
            name='city',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rent',
            name='city',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='walk',
            name='city',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
    ]
