# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityfinderapp', '0003_auto_20160211_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=None, max_length=20)),
                ('state', models.CharField(default=None, max_length=20)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('median_age', models.FloatField(blank=True, max_length=500, null=True)),
                ('age_depend_ratio', models.FloatField(blank=True, max_length=500, null=True)),
                ('old_age_depend_ratio', models.FloatField(blank=True, max_length=500, null=True)),
                ('child_depend_ratio', models.FloatField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
