# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cityfinderapp', '0004_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=None, max_length=20)),
                ('state', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='academic',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cityfinderapp.City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='age',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityfinderapp.City'),
        ),
        migrations.AlterField(
            model_name='col',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityfinderapp.City'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityfinderapp.City'),
        ),
        migrations.AlterField(
            model_name='hisp',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityfinderapp.City'),
        ),
        migrations.AlterField(
            model_name='lgbt',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityfinderapp.City'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityfinderapp.City'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityfinderapp.City'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityfinderapp.City'),
        ),
    ]
